### ISSUE TITLE
MLC-LLM Predictions with High Time Consumption

### ISSUE THREAD

**Issue by Madhu000** [mlc-ai/mlc-llm#1330]
I am using this mlc-chat-Llama-2-13b-chat-hf-q4f16_1 in A100 GPU to infer the output in zero-shot scenario but it is showing 10 hrs for to generate a label for 10k sentence. Is there anyway to make the process faster. Here is ipnb link [link](https://drive.google.com/file/d/111nf7JuIVx4fpukDs2IR1BWkc7fk_YsZ/view?usp=sharing. ). Please help me out. Thanks in advance.

**Comment by Madhu000** [comment]
Is there any clue on this issue?

**Comment by davidpissarra** [comment]
Hi @Madhu000, 10 hours for 10k sequences will give ~3.6 sec per sequence. This is normal since at this moment ChatModule only supports single sequence requests (`batch_size = 1`). Currently, part of the effort in MLC-LLM is to add batching support (multiple requests computed in parallel) to take advantage of GPU parallelism, and consequently reduce the average inference time per request. Stay tuned! (https://github.com/mlc-ai/mlc-llm/pulls?q=serving)

**Comment by Madhu000** [comment]
Thanks for your reply.. But using vLLM the inference time is very much less which is half an hour. Can you tell me the explanation behind this.

**Comment by davidpissarra** [comment]
vLLM supports the system to continuously batch sequences together, increasing GPU utilization, and therefore significantly increasing the overall throughput. The in-progress efforts on the MLC inference serving engine will allow MLC to support some of these techniques (e.g., PagedAttention through KV Cache pages), and thus reduce the average inference time.
