### ISSUE TITLE
Provide Instructions for adding and testing custom conversation template?

### ISSUE THREAD

**Issue by kmn1024** [mlc-ai/mlc-llm#1347]
## 🚀 Feature
Please provide instructions for adding and testing a new conversation template.

## Motivation
I have pretrained a model with (unfortunately) non-standard conversation template. The model builds fine, and the weights convert fine, but it requires a new conversation template. I would think that this is a fairly common occurrence within the community.

Also, it seems like it should be quite straightforward - adding a new function to conv_templates.cc. But I'm not sure how to compile and test it. I am working off my local codebase, and when I try this:
```
from mlc_chat import ChatModule
from mlc_chat.callback import StreamToStdout
cm = ChatModule(model="dist/pretrained-chat-instr_chat_chatint-1unlike-q4f16_1", lib_path="dist/pretrained-chat-instr_chat_chatint-1unlike-q4f16_1/pretrained-chat-instr_chat_chatint-1unlike-q4f16_1-opencl.so")
```

I still get "Unknown conversation template: custom_template_1", despite already adding custom_template_1 to conv_templates.cc (but again, I have no idea how to build the cpp code, so I'm not surprised by the error).

**Comment by CharlieFRuan** [comment]
Adding on, if you add a conversation template in `conv_templates.cc` (assuming you followed steps similar to this https://github.com/mlc-ai/mlc-llm/pull/956), you need to build mlc_chat from source: https://llm.mlc.ai/docs/deploy/cli.html#option-2-build-mlc-runtime-from-source.

Then afterward, either use `pip install -e .` inside `mlc-llm/python/`or edit the `PYTHONPATH` to be able to `import mlc_chat` in Python. That is, instead of importing `mlc_chat` from [the prebuilt package](https://llm.mlc.ai/docs/install/mlc_llm.html#option-1-prebuilt-package), you'd need to import it by first building it from source.
