### ISSUE TITLE
[Question] few shot prompting with ChatModule.generate

### ISSUE THREAD

**Issue by alecda573** [mlc-ai/mlc-llm#1902]
## ❓ General Questions
I am curious how to use the chatModule to perform few shot prompting as I would with HF.
Specifically, feed a structure as the following
message = [
    {"role": "system", "content": "DESCRIPTION OF THE LLMs TASK"},
    {"role": "user", "content": "FIRST EXAMPLE INPUT"},
    {"role", "assistant", "content", "EXPECTED OUTPUT FROM THE SYSTEM"},
    {"role": "user", "content": "SECOND EXAMPLE INPUT"},
    {"role", "assistant", "content": "EXPECTED OUTPUT FROM THE SYSTEM"},
    {"role", "user", "content": "EXAMPLE WE WANT THE LLM TO NOW GENERATE A RESPONSE TO"}
]

**Comment by shreygupta2809** [comment]
I am not entirely sure but you might be able to use the above message list you provided directly using mlc_llm.serve. We are currently in the works of updating the documentation for this however in the meantime you can explore and use the Rest API https://llm.mlc.ai/docs/deploy/rest.html [though it will be soon deprecated and updated with Serve] or to use Serve you can do:
Starting the server:
```bash
$ python -m mlc_llm.serve.server --model MODEL --model-lib-path MODEL_LIB_PATH [--device DEVICE] [--max-batch-size MAX_BATCH_SIZE] [--max-total-seq-length MAX_TOTAL_SEQ_LENGTH] [--prefill-chunk-size PREFILL_CHUNK_SIZE] [--enable-tracing] [--host HOST] [--port PORT] [--allow-credentials] [--allowed-origins ALLOWED_ORIGINS] [--allowed-methods ALLOWED_METHODS] [--allowed-headers ALLOWED_HEADERS]
```
and to send a request
```python
import requests

# Get a response using a prompt without streaming
payload = {
   "model": "./dist/Llama-2-7b-chat-hf-q4f16_1-MLC/",
   "messages": [
      {"role": "user", "content": "Hello! Our project is MLC LLM."},
      {
            "role": "assistant",
            "content": "Hello! It's great to hear about your project, MLC LLM.",
      },
      {"role": "user", "content": "What is the name of our project?"},
   ],
   "stream": False,
   # "n": 1,
   "max_tokens": 300,
}
r = requests.post("http://127.0.0.1:8080/v1/chat/completions", json=payload)
choices = r.json()["choices"]
for choice in choices:
   print(f"{choice['message']['content']}\n")
```
Instead of having different messages for each example, a possibility worth exploring might also be keeping all information in the 1st user message, but that is dependent on how you might like to do prompting.

**Comment by shreygupta2809** [comment]
Hopefully above solution has addressed your problem. Closing the issue. Kindly feel free to open another one.
Thanks
