### ISSUE TITLE
[Bug]  No module named mlc_llm.__main__

### ISSUE THREAD

**Issue by panghongtao** [mlc-ai/mlc-llm#1956]
## To Reproduce

W9057210@PAW9057210 MINGW64 /f/project/mlc-llm (main)
$ python -m mlc_llm convert_weight dist/models/Llama-2-7b-chat-hf/ --quantization q4f16_1 -o dist/Llama-2-7b-chat-hf-q4f16_1-MLC
C:\ProgramData\anaconda3\python.exe: No module named mlc_llm.main; 'mlc_llm' is a package and cannot be directly executed

I tried to use the new command, and there was another error. How do I handle this error?

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA):
 - Operating system (e.g. Ubuntu/Windows/MacOS/...):
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...)
 - How you installed MLC-LLM (`conda`, source):
 - How you installed TVM-Unity (`pip`, source):
 - Python version (e.g. 3.10):
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

**Comment by MasterJH5574** [comment]
Hi @panghongtao, I also ran into this before. It might be possible that you need to first remove all the `.pyc` files. The reason is likely because our old flow deprecation and rename a few days ago, and there are some local Python “caches” that are not updated together with the deprecation and rename.

Here is the stackoverflow question I referred to https://stackoverflow.com/questions/52477683/importerror-bad-magic-number-in-time-b-x03-xf3-r-n-in-django.

**Comment by panghongtao** [comment]
> Hi @panghongtao, I also ran into this before. It might be possible that you need to first remove all the `.pyc` files. The reason is likely because our old flow deprecation and rename a few days ago, and there are some local Python “caches” that are not updated together with the deprecation and rename.
> 
> Here is the stackoverflow question I referred to https://stackoverflow.com/questions/52477683/importerror-bad-magic-number-in-time-b-x03-xf3-r-n-in-django.

There is no.py file in my project. Cleaning these files is cleaning python? I tried to create a new python environment using conda. But this error still occurs. I don't know if this solution will solve the problem. Because I have multiple projects on my computer. I'm worried about how deleting.py files will affect other projects.

**Comment by shreygupta2809** [comment]
`.pyc` files compiled Python source and once you run your source program they are created again so this shouldn't cause any issues with your other projects as long you have the source for them. Otherwise, you can modify that command to only delete .pyc files in that particular folder: `find . -name <PATH_TO_MLC>*.pyc -delete`

**Comment by shreygupta2809** [comment]
Hopefully above solutions have addressed your problem, closing the issue. Kindly feel free to open another one in case any other problem arises.
Thanks
