### ISSUE TITLE
[Question] Is it possible to run it only on the CPU of an Android phone? 

### ISSUE THREAD

**Issue by yuguolong** [mlc-ai/mlc-llm#3056]
## ❓ General Questions

Can I set it to run only on the CPU on an Android phone? Or will an Android phone without a GPU be unable to run mlc-llm?
My goal is to test the speed of execution on both the CPU and GPU.

**Comment by MasterJH5574** [comment]
Hi @yuguolong thank you for the question. Right now we don't support running with CPU so you need a GPU to run mlc on Android phones.

**Comment by alexdsh** [comment]
add the ability to load other models, except for those that are by default. Make a choice from the local storage. Is it possible to somehow limit the level of loading of the graphics core, to at least 90%, since when the model is running, the phone freezes completely, including stopping the interface update (I generally just have a clean screen, white).

**Comment by yuguolong** [comment]
Hi @MasterJH5574, thank you for your reply, I have understood the situation.
