### ISSUE TITLE
[Bug]  python -m mlc_chat.rest ERROR

### ISSUE THREAD

**Issue by lorentz-wu** [mlc-ai/mlc-llm#329]
## 🐛 Bug

python -m mlc_chat.rest ERROR

## To Reproduce

File "/data/myw/mlc-llm/python/mlc_chat/libinfo.py", line 72, in find_lib_path
    raise RuntimeError(message)
RuntimeError: Cannot find libraries: libmlc_llm_module.so
List of candidates:
/data/mlc-llm/python/mlc_chat/libmlc_llm_module.so
/data/mlc-llm/build/libmlc_llm_module.so
/data/mlc-llm/build/Release/libmlc_llm_module.so
/anaconda3/envs/mlc-llm-env/lib/libmlc_llm_module.so
/usr/local/cuda/lib64/libmlc_llm_module.so
libmlc_llm_module.so

**Comment by junrushao** [comment]
Seems that you didn't build any `libmlc_llm_module.so`..Could you double check? Also CC @sudeepag @Kathryn-cat if you guys could help elaborate how to obtain `libmlc_llm_modyle.so`

**Comment by sudeepag** [comment]
@lorentz-wu We're in the process of making the module available via a python package, but in the mean time you need to first build the CLI from source (which will generate `libmlc_llm_module.so`) in order to use the REST API. Please check out the instructions [here](https://mlc.ai/mlc-llm/docs/install/tvm.html).

**Comment by tqchen** [comment]
closing due to inactive status, feel free to reopen if the latest version still have issue
