### ISSUE TITLE
build.py loops too long

### ISSUE THREAD

**Issue by njuhang** [mlc-ai/mlc-llm#500]
I use command
python build.py --model /mnt/c/vicuna-v1-7b --quantization q4f16_0 --target android-dylib --max-seq-len 768
But the process have been running for several hours and get stuck at the point "- Dispatch to pre-scheduled op: fused_NT_matmul2_multiply" can't come to an end. 
But before I update my repo code, the process will finish in about 0.5 hours. I think there may be some bugs in this procedure.

**Comment by junrushao** [comment]
It shouldn’t take that long. On our end, it’s usually less than a few seconds.

Could you please share your TVM installation configuration (https://mlc.ai/mlc-llm/docs/install/tvm.html#validate-installation), conda configuration (https://mlc.ai/mlc-llm/docs/install/conda.html#validate-installation) and the CPU/RAM of workstation so that we could look into this issue?

**Comment by njuhang** [comment]
Sorry, I can't open the links you provided. What't more, https://mlc.ai/mlc-llm/ doesn't work either.

**Comment by Hzfengsy** [comment]
It may because of the GFW as you are in China mainland :)

**Comment by junrushao** [comment]
@njuhang you may read the raw RST: https://github.com/mlc-ai/mlc-llm/blob/main/docs/install/tvm.rst

I'm a bit curious though, given https://mlc.ai/mlc-llm/ is hosted via GitHub pages, does it mean the entire GitHub is blocked in China?

**Comment by njuhang** [comment]
OK, maybe it's matter of my network GFW, thanks a lot everyone.

**Comment by njuhang** [comment]
OK, maybe it's matter of my network GFW, thanks a lot everyone.
