### ISSUE TITLE
[Bug] Andriod Built Error: every buttons on the ChatView.kt page can't be clicked

### ISSUE THREAD

**Issue by willswordh** [mlc-ai/mlc-llm#539]
Hi, I followed the android build instruction, the buttons on ChatView.kt page are not working. The text input can work. What can the potential reasons behind it?

**Comment by tteichmann** [comment]
Pixel owner here, with similar issues as discussed above. I understand this is because Google does not provide OpenCL on any of their Pixel devices, which will presumably not change any time soon.

Does this just mean I am unlucky or are there any plans to support Android devices without access to OpenCL in the future?

Thanks!

**Comment by cyx-6** [comment]
@willswordh @tteichmann Sorry for replying late. Please try new [apk](https://github.com/mlc-ai/binary-mlc-llm-libs/blob/main/mlc-chat.apk).
