### ISSUE TITLE
[Question] when support Llama2 on Android

### ISSUE THREAD

**Issue by davidjohn001** [mlc-ai/mlc-llm#569]
## 🚀 Feature

currently it support iphone/cuda/metal/vulkan
so when support Llama-2-7b-chat-hf on **Android**?

**Comment by twiceyuan** [comment]
With the current project structure, it looks like you just need to modify the `MLCChat/app/src/main/assets/app-config.json` file and rebuild.

I forked a version to try this out, but since I don't have access to `meta-llama/Llama-2-7b-chat-hf`, I'm using a model file from another HuggingFace repository (`daryl149/llama-2-7b-chat-hf`), if necessary, you can try llama2-7b-chat by directly compiling the Android project from my fork:

https://github.com/twiceyuan/mlc-llm

Model weight file + android.tar file:

https://huggingface.co/twiceYuan/llama-2-7b-chat-hf-q3f16_1

**Comment by willswordh** [comment]
@twiceyuan  Hi! I am wondering in your built android app, can the model be added? On my built app, only the vicuna v1.1 can work. The models loaded directly though url or added through ADB can't work.

**Comment by twiceyuan** [comment]
@willswordh According to my understanding, whether a model is supported depends on whether you have completed its `build.py` operation before `android/prepare_libs.sh` is executed. For the Android platform, the dependent file is generally `[model-id]_android.tar`.

So I guess you should only built the vicuna v1.1 model locally? so directly adding other model urls or `adb push` to the weights file will not work. If you want to try llama2, you can try the android.tar and corresponding weights file from HuggingFace mentioned in my previous reply.

**Comment by IgnacioTechie** [comment]
@twiceyuan, thanks for this. Any chance you could share the 4-bit quantized build of the model (q4f16 rather than q3f16)? I've been trying to make the build in my machine but no success so far. Encouraged for what you did. Thanks!

**Comment by cyx-6** [comment]
Sorry for replying late! Please try new [apk](https://github.com/mlc-ai/binary-mlc-llm-libs/blob/main/mlc-chat.apk) with support of llama-2.
