### ISSUE TITLE
Unclear how to specify model for REST API

### ISSUE THREAD

**Issue by hamelsmu** [mlc-ai/mlc-llm#620]
I'm following the [docs for the REST API](https://mlc.ai/mlc-llm/docs/deploy/rest.html)

It's not clear how to specify the model you want to load into the server.  It looks like something is hardcoded to look for `vicuna-v1-7b` but I don't have that.  Here is what is in my `dist/` folder:

```
$  tree -L 2 dist/

dist/
├── Llama-2-7b-hf-q4f16_0
│   ├── Llama-2-7b-hf-q4f16_0-cuda.so
│   ├── mod_cache_before_build.pkl
│   └── params
└── models
    └── Llama-2-7b-hf
```

This is the error when I run the server [per the instructions]((https://mlc.ai/mlc-llm/docs/deploy/rest.html))

```
$ python3 -m mlc_chat.rest --device-name cuda

INFO:     Started server process [49903]
INFO:     Waiting for application startup.
ERROR:    Traceback (most recent call last):
  File "/home/ubuntu/mambaforge/envs/mlc/lib/python3.10/site-packages/starlette/routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/home/ubuntu/mambaforge/envs/mlc/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/home/ubuntu/mambaforge/envs/mlc/lib/python3.10/site-packages/mlc_chat/rest.py", line 41, in lifespan
    raise ValueError(
ValueError: Unable to find vicuna-v1-7b-q3f16_0-cuda.so at dist/vicuna-v1-7b-q3f16_0/vicuna-v1-7b-q3f16_0-cuda.so or dist/prebuilt/lib/vicuna-v1-7b-q3f16_0-cuda.so.
```

**Comment by tqchen** [comment]
Here is one example through python API https://github.com/mlc-ai/notebooks/blob/main/mlc-llm/tutorial_chat_module_getting_started.ipynb

Thanks for checking in, atm it works on vulkan, and feel free to swap out for cuda. Love to see suggestions on APIs as well

**Comment by junrushao** [comment]
The python API is quite new and is expected to be well-documented in the incoming 2-4 weeks.

On your particular case, I believe [this flag](https://github.com/mlc-ai/mlc-llm/blob/c40be6a210e4d8844b8a65951bcfaa44b528b8f9/python/mlc_chat/rest.py#L69-L69) allows you to use Llama2 instead of Vicuna.

i.e.

```diff
- python3 -m mlc_chat.rest --device-name cuda
+ python3 -m mlc_chat.rest --device-name cuda --model Llama-2-7b-hf --quantization q4f16_1
```

Usually, you may obtain all the flags available with the instruction below:

```bash
python3 -m mlc_chat.rest --help
```

BTW, the C++ / Swift / Java / JavaScript APIs are relatively stable if you are interested. We have an iOS app that you could actually download and try out on your own phone (as long as it has larger than 6GB RAM): https://apps.apple.com/us/app/mlc-chat/id6448482937.

I have opened up a repo of reproducible dockerfiles for performance benchmarking (now only CUDA is available): https://github.com/junrushao/llm-perf-bench/, where the MLC numbers are from C++ APIs, if you are interested in more details.

**Comment by Kathryn-cat** [comment]
Hi @hamelsmu , thanks for the issue! We're improving the Python API and the Rest API this week, and I've opened up a tracking issue to demonstrate our progress. We'll bring more documentation and examples as well :)

**Comment by sudeepag** [comment]
https://github.com/mlc-ai/mlc-llm/pull/681 will address this issue.

**Comment by Kathryn-cat** [comment]
Hi @hamelsmu , we have updated the docs on REST API and Python API on how to specify the model with demos. Let us know if you have any more questions!

**Comment by hamelsmu** [comment]
Thanks folks I'll give it a go now and let you know if there are any issues 🙇🏽 

Impressive level of follow up 🎉
