### ISSUE TITLE
Pixel 7 support / OpenCL

### ISSUE THREAD

**Issue by AndysDeepAbstractions** [mlc-ai/mlc-llm#640]
## ❓ General Question

Your Website states:

"It does not yet work on Google Pixel due to limited OpenCL support. We will continue to bring support and welcome contributions from the open source community. You can also check out our GitHub.."

Is this the way to go to run the MLC APK on a Pixel 7:

https://github.com/reekotubbs/Pixel_OpenCL_Fix ?

Thanks for your Advice !

**Comment by brianjking** [comment]
Also wondering myself, @AndysDeepAbstractions -- on my pixel 7 pro I can download MLC and download models, but clicking the button to perform an inference results in nothing happening.

**Comment by alex4o** [comment]
I have opened a pull request that allows you to do that, you can try to build with it and the modified tvm that it links to.
https://github.com/mlc-ai/mlc-llm/pull/723

**Comment by AndysDeepAbstractions** [comment]
It's already merged 👍

**Comment by AndysDeepAbstractions** [comment]
Will the official APK be updated anytime soon?

**Comment by alex4o** [comment]
If you want to try it out without building it yourself you can try my build https://github.com/alex4o/mlc-ai-mlc-llm/releases/tag/one

**Comment by nealmcb** [comment]
I was a bit confused. I hope this helps.

I see this is closed, and a patch was merged a month ago, but  the mlc-chat.apk binary version is still dated June 7, as seen here: https://github.com/mlc-ai/binary-mlc-llm-libs/commits/main/mlc-chat.apk

I guess this was closed since the main goal here is publishing the source. But I'll echo the request above to update the official apk that is linked to from the instructions at https://mlc.ai/mlc-llm/docs/get_started/try_out.html

In the meantime, I tried the version that alex4o offers above, and it works - many thanks!

Though note it just has the vicuna-7b-v1.5-q4f16_1 version, not the RedPajamas model.

**Comment by junrushao** [comment]
Note: pixel is supported via the latest release. https://github.com/mlc-ai/mlc-llm/pull/723

**Comment by ChenYuYeh** [comment]
> If you want to try it out without building it yourself you can try my build https://github.com/alex4o/mlc-ai-mlc-llm/releases/tag/one

Hi I tried this version on a Chromebook (since the official apk will crash with the same missing libopencl), it has no crash but cannot submit any input.   The submit button is always gray-out. Any idea?
![IMG_20240830_080052_69.jpg](https://github.com/user-attachments/assets/4df87345-fcfd-4cf6-be29-da608a47c4b0)
