### ISSUE TITLE
[Question] Cannot find "mlc-chat-config.json" in path ""dist"/RedPajama-INCITE-Chat-3B-v1-q4f16_1

### ISSUE THREAD

**Issue by TanmayDoesAI** [mlc-ai/mlc-llm#730]
## ❓ General Questions

I followed the steps mentioned at https://mlc.ai/mlc-llm/docs/get_started/try_out.html 
and i got this after running 
(mlc-chat-venv) D:\textgen\dist\prebuilt>mlc_chat_cli --local-id RedPajama-INCITE-Chat-3B-v1-q4f16_1

Cannot find "mlc-chat-config.json" in path ""dist"/RedPajama-INCITE-Chat-3B-v1-q4f16_1
 because the files are in prebuilt folder i think which is a problem

**Comment by CharlieFRuan** [comment]
Thanks for the question @TanmayDoesAI! Could you try invoking `mlc_chat_cli` under `D:\textgen`?

**Comment by TanmayDoesAI** [comment]
@CharlieFRuan ohhhh, I completely forgot, that was a rookie error, thanks for help!

**Comment by Myracodes20** [comment]
hey, I tried a similar thing 
firstly cloned the llama 2 70b
(mlc-chat-venv) D:\text-gen\dist\prebuilt>git clone https://huggingface.co/mlc-ai/mlc-chat-Llama-2-70b-chat-hf-q3f16_1

then got this
(mlc-chat-venv) D:\text-gen>mlc_chat_cli --local-id Llama-2-70b-chat-hf-q3f16_1
Use MLC config: "D:\\text-gen\\dist\\prebuilt\\mlc-chat-Llama-2-70b-chat-hf-q3f16_1\\mlc-chat-config.json"
Use model weights: "D:\\text-gen\\dist\\prebuilt\\mlc-chat-Llama-2-70b-chat-hf-q3f16_1\\ndarray-cache.json"
Cannot find library "Llama-2-70b-chat-hf-q3f16_1-vulkan.dll" in "dist"/prebuilt/lib or other search paths

@CharlieFRuan could you help with this?

**Comment by CharlieFRuan** [comment]
Hi @Myracodes20, unfortunately llama2 70b is only supported in `-metal.so` and `-webgpu.wasm`, as shown in [this repo](https://github.com/mlc-ai/binary-mlc-llm-libs) (the one you cloned in the tutorial), which contains all the model libraries. 

This is because llama2 70b requires a great amount of memory (M2 Max can run it). We are currently working towards making 70b deployable in more platforms/devices.

In the mean time, you could perhaps try out Llama2 13B/7B, which are supported in many more platforms.

**Comment by Myracodes20** [comment]
oh okay, thanks for the help!
