### ISSUE TITLE
Speed benchmark compare with llama.cpp

### ISSUE THREAD

**Issue by luohao123** [mlc-ai/mlc-llm#75]
hello ,does there any speed throughout benchmark comparing with llama.cpp?

**Comment by junrushao** [comment]
The technical path we are using are quite different from Llama.cpp. MLC LLM primarily uses a compiler to generate efficient 
code targeting multiple CPU/GPU vendors, while Llama.cpp focuses on handcrafting. It is certainly possible to compare performance, but I personally prefer that it's a less prioritized item for us, because GPU is supposed to be way faster than CPUs for deep learning workloads.

**Comment by escorciav** [comment]
Great question. @junrushao What about DSP support in Mobile devices? I heard it's possible to hook up DSP onto TVM.

@luohao123 do you know if llama.cpp plans to add support for DSP chips of high-end cellphones?

**Comment by taowen** [comment]
when GPTQ support is merged, it would be interesting to compare with https://github.com/turboderp/exllama
