### ISSUE TITLE
[Bug] Can't change the model in "mlc-chat-config.json"

### ISSUE THREAD

**Issue by willswordh** [mlc-ai/mlc-llm#834]
## 🐛 Bug

I tried to add the example of system prompt change to my vicuna 1.3 model in "mlc-chat-config.json" according to the doc, which is "You are not Vicuna, your name is Guanaco, now let's chat!" However, the model still answer back "I am vicuna." The change of temperature and max-gel-len also are not working. Can anybody take a look of it? Thanks!

**Comment by CharlieFRuan** [comment]
Could you perhaps provide the code or environment so that we could replicate the bug?

I just tried [the example in the documentation](https://mlc.ai/mlc-llm/docs/deploy/python.html#configure-mlcchat-in-python) using Python API, it still seems to work (shown in screenshot). Directly changing the `mlc-chat-config.json` should be equivalent.

![image](https://github.com/mlc-ai/mlc-llm/assets/53290280/96cecd06-7de7-42d1-ab9f-5f5e1cf98f66)

**Comment by willswordh** [comment]
@CharlieFRuan Thanks for your quick response and help! I am running it on the android platform. So I changed the mlc-chat-config.json and added the system prompt as the one I posted previously. Then I added the model to the android device and load it inside the app. The response is still the same as the this config changes is not processed.

**Comment by tqchen** [comment]
maybe it is easer to check the python API first since sometimes system prompt may not able to affect the model behavior as much
