### ISSUE TITLE
[Question] add model url failed in android

### ISSUE THREAD

**Issue by LitenBuzzTh** [mlc-ai/mlc-llm#888]
## ❓ General Questions

Hi

thanks for this opportunity on making LLMs run locally on android. 

My device is  : samsung s22 ultra

the default models that appear on app launch are able to download and run just fine

but when I add other model URLs it just fails. the ones I tried are :

https://huggingface.co/jetro30087/vicuna-Wizard-7B-Uncensored-android-q4f16_0

https://huggingface.co/acalatrava/mlc-chat-luna-ai-llama2-7b-chat-uncensored-q3f16_1/tree/main

https://huggingface.co/jetro30087/vicuna-Wizard-7B-Uncensored-android-q3f16_0

🤔 is there any specific url formatting that I should consider?

**Comment by Lanssi** [comment]
Maybe you can refer to adding model by url on iOS. Check the steps and refer to the sample url in it.
Following is the link:
https://mlc.ai/mlc-llm/docs/prebuilt_models.html

**Comment by asl97** [comment]
Every link I tried so far, all state that it's not supported, with the current latest [apk](https://github.com/mlc-ai/binary-mlc-llm-libs/blob/a6b0a4cdaef24725aaf710d4a05ea8b13da2ce42/mlc-chat.apk) 

Even the single other model listed for android on https://mlc.ai/mlc-llm/docs/prebuilt_models.html , the very same link shown as a sample in the app itself

https://github.com/mlc-ai/mlc-llm/assets/4752645/0df113e0-fc75-469d-8f63-ab847b6022fd

It would be helpful if someone can provide an example link that actually works

**Comment by junrushao** [comment]
We revamped our tutorials lately to include instructions on building a model for Android from Huggingface: https://llm.mlc.ai/docs/deploy/android.html#compile-pytorch-models-from-huggingface.

For now, we haven’t been focusing on officially expanding model coverage yet - it’s just not the right timing. but if you encounter any issues building models for Android on your end, please reach out and we are happy to help!

**Comment by asl97** [comment]
> but if you encounter any issues building models for Android on your end, please reach out and we are happy to help!

I assume the guide isn't for building on android for android, I encountered so many issue that I just gave up and `rm -r` the repo, I might have better luck in a proot distro but I already `rm` it.

Not to mention the final step of building the apk which I didn't even see since I was only on step 1* of this guide which I misunderstood the android tab as building on android from a quick glance without reading the whole thing, and who knows how much more complicated that would be on android if it's even possible.

*https://llm.mlc.ai/docs/compilation/compile_models.html#install-mlc-llm-package

**Comment by KingAlejandro** [comment]
>  Screenrecorder-2023-09-28-11-25-14-664.mp4 

Has the feature that allows to add custom models in the compiled app been removed? I can't seem to find it
