### ISSUE TITLE
Error reported when executing 'mlc_chat_cli'

### ISSUE THREAD

**Issue by linjie830914** [mlc-ai/mlc-llm#912]
## ❓ General Questions
![image](https://github.com/mlc-ai/mlc-llm/assets/7983557/84e5de75-fc6c-4ca5-a580-d06c9c44beba)

**Comment by linjie830914** [comment]
mlc_chat_cli --model mlc-chat-Llama-2-7b-chat-hf-q4f16_1

**Comment by MasterJH5574** [comment]
Hi @linjie830914, the error message suggests `VK_ERROR_INCOMPATIBLE _DRIVER` and may be because the Vulkan driver has not been installed or wrongly installed or the device is incompatible. Could you follow https://www.vulkan.org/tools#vulkan-gpu-resources and make sure the driver is correctly installed?
