### ISSUE TITLE
error：we cannot find `mlc-chat-config.json`

### ISSUE THREAD

**Issue by linjie830914** [mlc-ai/mlc-llm#953]
## ❓ General Questions

(mlc-chat-venv) D:\Llama\prebuilt>mlc_chat_cli --model Llama-2-7b-chat-hf-q4f16_1
[09:28:41] C:\Miniconda\envs\mlc-llm-build\conda-bld\mlc-chat-cli-nightly-package_1693804235111\work\cpp\cli_main.cc:339: The model folder provided does not seem to refer to a valid mlc-llm model folder. **Specifically, we cannot find `mlc-chat-config.json`, a required file**. You should provide a path that contains the file. According to your input `Llama-2-7b-chat-hf-q4f16_1`, we looked at folder(s):
- Llama-2-7b-chat-hf-q4f16_1
- dist/prebuilt/Llama-2-7b-chat-hf-q4f16_1
- dist/Llama-2-7b-chat-hf-q4f16_1/params
- dist/prebuilt/mlc-chat-Llama-2-7b-chat-hf-q4f16_1
Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.
![image](https://github.com/mlc-ai/mlc-llm/assets/7983557/aba18fd8-5cab-42a3-9cfa-da349d86ee9e)

**Comment by wangxu569** [comment]
Maybe you can try to place chatglm2-6b-q4f16_1 under the /mlc-llm/dist/ path, and execute mlc-chat-cli under the /mlc-llm path.

**Comment by linjie830914** [comment]
I am using the Windows 11 operating system. How is the path planning appropriate under the Windows system?

**Comment by linjie830914** [comment]
@wangxu569 Hello, could you please help me see how to solve this problem? Thank you!

**Comment by wangxu569** [comment]
> @wangxu569 Hello, could you please help me see how to solve this problem? Thank you!

Maybe you can take a look : https://mlc.ai/mlc-llm/docs/get_started/try_out.html

**Comment by Sing-Li** [comment]
@linjie830914 if you have not figured it out yet ....

![image](https://github.com/mlc-ai/mlc-llm/assets/122633/9f7a6e7a-c247-4a37-b374-8b7a6cf1fc65)

You want to create a `D:\mcl-chat\dist`   directory, then move the `prebuilt` directory (and all its contents) over.

After that, change directory into `D:\mlc-chat`  and then run your command again.  It should work.

**Comment by linjie830914** [comment]
Thank you, I'll give it a try.

**Comment by linjie830914** [comment]
![image](https://github.com/mlc-ai/mlc-llm/assets/7983557/75150886-38c1-48b5-a20d-f14cf6191119)
After modifying the path, the model can be loaded, but new issues have been encountered
![image](https://github.com/mlc-ai/mlc-llm/assets/7983557/d1a04880-4ad9-4338-bded-757a4ceff390)

**Comment by linjie830914** [comment]
Is it out of memory?

**Comment by CharlieFRuan** [comment]
Hi @linjie830914, based on the log, it does seem to be an OOM issue. Would you mind sharing the amount of memory you have?

Or perhaps you could try [Llama-2-7b-q3f16_1](https://huggingface.co/mlc-ai/mlc-chat-Llama-2-7b-chat-hf-q3f16_1), which is smaller due to int3 quantization as opposed to int4.

Alternatively, perhaps a smaller model like [RedPajama-INCITE-Chat-3B-v1-q4f16_1](https://huggingface.co/mlc-ai/mlc-chat-RedPajama-INCITE-Chat-3B-v1-q4f16_1), which has 3B parameters as opposed to 7B.

**Comment by tqchen** [comment]
Closing for now due to inactive status, feel free to open new ones

**Comment by csy94cfy** [comment]
Hi, did you solved your question? I meet the same situation, my graphic card is 4060ti 16G,  I don't know how to solve the same question like
`Stack trace not available when DMLC_LOG_STACK_TRACE is disabled at compile time.`

**Comment by CharlieFRuan** [comment]
Hi @csy94cfy, the workflow described in this issue is deprecated as we no longer auto-lookup `mlc-chat-config.json`. Please refer to the most up-to-date documentation: 
- Python Runtime: https://llm.mlc.ai/docs/deploy/python.html
- CLI Runtime: https://llm.mlc.ai/docs/deploy/cli.html
- Compile time: https://llm.mlc.ai/docs/compilation/compile_models.html
